name: "Post rom to telegram with banner and description"

on:
  workflow_dispatch:
    inputs:
      banner:
          description: 'link preview banner'
          required: true
          default: 'https://raw.githubusercontent.com/shenprjkt/project-banner/refs/heads/android-12.1/Alts-Mi8953-Banner.jpg'
      romname:
          description: 'Rom name'
          required: true
          default: 'LineageOS'
      android:
          description: 'Android Version/Rom Version example=20.0 T'
          required: true
          default: '20.0 T'
      type:
          description: 'Unofficial/Official'
          required: true
      date:
          description: 'Build Date'
          required: true
      maintainer:
          description: 'Maintainer'
          required: true
          default: '0xKANARIA'
      devicename:
          description: 'Codename Device'
          required: true
          default: 'MI8953'
      download:
          description: 'download & screenshots & changelog link'
          required: true
      support:
          description: 'Support Group'
          required: true
          default: 'https://t.me/MI8953'
      gapps:
          description: 'vanilla/gapps'
          required: true
          default: 'Vanilla'
      

env:
  TZ: Asia/Jakarta
  PHOTO: ${{ github.event.inputs.banner }}
  DEVICENAME: ${{ github.event.inputs.devicename }}
  ANDROID: ${{ github.event.inputs.android }}
  TYPE: ${{ github.event.inputs.type }}
  DATE: ${{ github.event.inputs.date }}
  MAINTAINER: ${{ github.event.inputs.maintainer }}
  DOWNLOAD: ${{ github.event.inputs.download }}
  ROMNAME: ${{ github.event.inputs.romname }}
  SUPPORT: ${{ github.event.inputs.support }}
  GAPPS: ${{ github.event.inputs.gapps }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Post Update
        run: |
          wget https://raw.githubusercontent.com/KanariaAlt/Android-CI/main/Common/post.sh
          bash post.sh

        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHAT_CH: ${{ secrets.CHAT_CH }}