name: "tmate ssh"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: setup 
        run: |
          export TERM=xterm && sudo apt update && sudo apt upgrade && sudo apt-get install tmate && sudo apt-get purge needrestart && sudo apt install openssh-server && sudo systemctl enable --now ssh && tmate -F
