name: "tmate ssh"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && sudo apt-get install tmate && tmate
